apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ include "appname" . }}-{{ include "orgname" . }}-nginx
data:
  default.conf: |
    server { # simple reverse-proxy
      listen       8080;
      listen       [::]:8080;
      server_name  localhost;
      access_log   /var/log/nginx/host.access.log  main;

      # serve static files
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
